import { NextPage } from "next";
import Head from "next/head";
import Content from "~/components/content";
import Header from "~/components/header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Astra Notepad</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
    </>
  );
}

export default Home
